#!/usr/bin/bash

# This script will run all services/workers for dockurr
# FOR TESTING/DEVELOPMENT ONLY

# shellcheck disable=SC2064
trap "kill -KILL -- -$$" EXIT

_tput() {
        if command -v tput > /dev/null; then
                tput "$@"
        fi
}

add_prefix() {  # usage: add_prefix name color
        prefix="$(_tput sgr0)"
        prefix="$prefix$(_tput setab "$2")"
        prefix="$prefix$(_tput bold)"
        suffix="$(_tput sgr0)"
        sed "s/^/$prefix$1$suffix: /"
}

print_banner() {
        # credits to this guy: https://gist.github.com/dhrp/5733652
        tput setaf green
        tput bold
        cat <<EOF
  _______
< dockurr >
  -------
      \           ##        .           
       \      ## ## ##       ==           
        \  ## ## ## ##      ===          
       /""""""""""""""""\___/ ===       
  ~~~ {~~ ~~~~ ~~~ ~~~~ ~~ ~ /  ===- ~~~ 
       \______ o          __/            
         \    \        __/             
          \____\______/                

EOF
        tput sgr0
}

print_banner

flask createdb

flask run --debug 2>&1 | add_prefix flask 125 &
celery \
        -A dockurr.make_celery worker \
        -l INFO 2>&1 | add_prefix celery-worker 130 &
celery \
        -A dockurr.make_celery beat \
        -S redbeat.RedBeatScheduler \
        -l INFO 2>&1 | add_prefix celery-beat 131 &
wait
